### ISSUE TITLE
Lack of multiport matcher in iptables

### ISSUE THREAD

**Issue by mkiol** [sailfish-on-dontbeevil/droid-hal-kernel-pine#9]
I've noticed that some iptables rules are not enabled in latest Pinephone SFOS build. For instance `/etc/connman/firewall.d/11-allow-udp-non-privileged-ports-firewall.conf` rules are not applied because `connman` reports an error: `Couldn't load match multiport':No such file or directory`.

Unfortunately lack of these iptables rules breaks some apps :(

It appears that root cause is that kernel is not configured with CONFIG_NETFILTER_XT_MATCH_MULTIPORT.

Would you be able to enable it?

Thank you for your great work!

**Comment by piggz** [comment]
Sure, can add that.

**Comment by piggz** [comment]
Added

**Comment by mkiol** [comment]
Thank you 😃
